// approaches:

// direct/raw data
// smooth - mean
// change - standard deviation

// thresholds
// when going over a certain threshold
// when going under a certain threshold
// hysteresis: on: over a certain threshold; off: under a (lower) threshold

// gating - only let data through when on / off


// states:
// high mean, low change - "rest - stretched"
// changing mean, high change - "to bend"
// low mean, low change - "rest - bend"
// changing mean, high change - "to stretch"
